"""
main.py — FastAPI application entry point for the VRPTW Delivery Route Optimizer.

Why this file exists:
    This is the HTTP layer that glues together the three specialist modules:
        distance.py      →  fetches a real-world travel-time matrix from Google Maps
        vrptw_solver.py  →  feeds that matrix into OR-Tools to find the optimal route
        models.py        →  defines the Pydantic request/response contracts

    Keeping the endpoint thin (validation + orchestration only) means each
    underlying module can be tested and reasoned about independently.

Running locally:
    cd backend
    uvicorn main:app --reload --port 8000

API docs (auto-generated by FastAPI):
    http://localhost:8000/docs       ← Swagger UI
    http://localhost:8000/redoc      ← ReDoc
"""

import urllib.parse
import logging

import requests as http_requests
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

from models import (
    DeliveryStop,
    OptimizeRouteRequest,
    OptimizeRouteResponse,
    OptimizedStop,
)
from distance import fetch_distance_matrix
from vrptw_solver import solve_vrptw

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(name)s  %(message)s")
logger = logging.getLogger("vrptw_api")

# ---------------------------------------------------------------------------
# App creation
# ---------------------------------------------------------------------------
app = FastAPI(
    title="VRPTW Delivery Route Optimizer",
    description=(
        "Optimises last-mile delivery routes using the Vehicle Routing Problem "
        "with Time Windows (VRPTW).  Accepts a depot address and a list of "
        "customer addresses with slot preferences, and returns an ordered "
        "delivery sequence with ETA and Google Maps navigation links."
    ),
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

# ---------------------------------------------------------------------------
# CORS — allow the React dev server (Vite default: 5173) and production builds
# ---------------------------------------------------------------------------
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "https://opti-route-nu.vercel.app",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# Time-window definitions in minutes from 9:00 AM
# Slot 1:  9:00 AM – 12:00 PM  →  [  0, 180]
# Slot 2:  1:00 PM –  5:00 PM  →  [240, 480]
# Depot:   open all day         →  [  0, 540]
# ---------------------------------------------------------------------------
_SLOT_WINDOWS = {
    1: (0, 180),
    2: (240, 480),
}
_DEPOT_WINDOW = (0, 540)


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@app.get("/health", tags=["Meta"])
def health_check() -> dict:
    """
    Lightweight liveness probe.

    Returns a JSON object confirming the service is running.  Useful for
    container health checks and uptime monitors.

    Returns:
        dict: {"status": "ok", "service": "<name>"}
    """
    return {"status": "ok", "service": "VRPTW Delivery Route Optimizer"}


@app.post(
    "/optimize-route",
    response_model=OptimizeRouteResponse,
    tags=["Route Optimization"],
    summary="Optimise a set of delivery stops",
    response_description="Ordered delivery sequence with arrival times and Maps links",
)
def optimize_route(request: OptimizeRouteRequest) -> OptimizeRouteResponse:
    """
    Core endpoint — accepts delivery addresses and returns the optimal route.

    Pipeline (5 steps):
        1.  Validate input (redundant with Pydantic but provides richer messages).
        2.  Call Google Maps Distance Matrix API to get real driving-time matrix.
        3.  Build the VRPTW data model (time windows, depot, service time).
        4.  Run the OR-Tools VRPTW solver.
        5.  Enrich the solution with Google Maps deep links and return.

    Args:
        request (OptimizeRouteRequest):
            JSON body with `depot_address` (str) and `deliveries`
            (list of {address, slot}).

    Returns:
        OptimizeRouteResponse:
            `success=True`, `total_stops`, `depot_address`, and `route`
            (ordered list of OptimizedStop objects).

    Raises:
        HTTPException 400:
            • Empty delivery list.
            • More than 20 stops requested.
            • An address is unroutable or ungeocoded.
            • Invalid slot value.
        HTTPException 422:
            OR-Tools found no feasible solution.  Guidance is returned in the
            detail string to help the user adjust their inputs.
        HTTPException 503:
            Google Maps API is unreachable (network error or quota exceeded).
    """
    # -----------------------------------------------------------------------
    # Step 1 — Input validation
    # (Pydantic already enforces types; this catches logical constraints.)
    # -----------------------------------------------------------------------
    if not request.deliveries:
        raise HTTPException(
            status_code=400,
            detail="Please add at least one delivery stop.",
        )

    if len(request.deliveries) > 20:
        raise HTTPException(
            status_code=400,
            detail=f"Maximum 20 delivery stops are supported; got {len(request.deliveries)}.",
        )

    logger.info(
        "Optimisation request: depot='%s', %d stops",
        request.depot_address,
        len(request.deliveries),
    )

    # -----------------------------------------------------------------------
    # Step 2 — Build the full address list and fetch the distance matrix
    #   Index 0 is always the depot; customers follow in request order.
    #   We pass this full list to Google Maps and get back M[i][j] = travel
    #   time in minutes from address i to address j.
    # -----------------------------------------------------------------------
    all_addresses = [request.depot_address] + [d.address for d in request.deliveries]

    try:
        time_matrix = fetch_distance_matrix(all_addresses)
    except ValueError as exc:
        # Surfaces geocoding failures ("cannot find route A→B") as 400 so
        # the user knows to fix their input rather than retry.
        logger.warning("Distance Matrix error: %s", exc)
        raise HTTPException(status_code=400, detail=str(exc))
    except http_requests.RequestException as exc:
        # Network-level failures are not the user's fault.
        logger.error("Google Maps API unreachable: %s", exc)
        raise HTTPException(
            status_code=503,
            detail=(
                "Could not reach the Google Maps API.  "
                "Check your internet connection or API key quota and try again."
            ),
        )

    logger.info("Distance matrix fetched (%d×%d)", len(time_matrix), len(time_matrix))

    # -----------------------------------------------------------------------
    # Step 3 — Build the VRPTW data model
    #   time_windows[0]   = depot window (open all day)
    #   time_windows[i>0] = customer window based on slot preference
    # -----------------------------------------------------------------------
    time_windows = [_DEPOT_WINDOW]  # depot is always index 0

    for delivery in request.deliveries:
        if delivery.slot not in _SLOT_WINDOWS:
            raise HTTPException(
                status_code=400,
                detail=(
                    f"Invalid slot '{delivery.slot}' for address '{delivery.address}'. "
                    "Allowed values: 1 (9 AM–12 PM) or 2 (1 PM–5 PM)."
                ),
            )
        time_windows.append(_SLOT_WINDOWS[delivery.slot])

    vrptw_data = {
        "time_matrix":  time_matrix,
        "time_windows": time_windows,
        "num_vehicles": 1,          # single driver; set > 1 for fleet routing
        "depot":        0,
        "service_time": 10,         # 10 min unloading time per delivery stop
        "addresses":    all_addresses,
    }

    # -----------------------------------------------------------------------
    # Step 4 — Run the OR-Tools VRPTW solver
    # -----------------------------------------------------------------------
    logger.info("Running OR-Tools VRPTW solver …")
    solution_stops = solve_vrptw(vrptw_data)

    if solution_stops is None:
        logger.warning("OR-Tools returned no feasible solution")
        raise HTTPException(
            status_code=422,
            detail=(
                "No feasible route found.  This usually means the time windows "
                "are too tight given the driving distances.  Try one or more of:\n"
                "  • Moving distant stops to Slot 2 (wider afternoon window)\n"
                "  • Reducing the number of stops in Slot 1\n"
                "  • Verifying that all addresses are in the same metro area"
            ),
        )

    logger.info("Solution found: %d stops", len(solution_stops))

    # -----------------------------------------------------------------------
    # Step 5 — Enrich with Google Maps deep links
    #   Format:  https://www.google.com/maps/dir/?api=1&destination=<encoded>
    #   This URL opens the Maps app on iOS/Android directly into navigation
    #   mode toward the destination — ideal for drivers on mobile.
    # -----------------------------------------------------------------------
    optimized_stops = []
    for stop in solution_stops:
        encoded_dest = urllib.parse.quote(stop["address"])
        maps_url = (
            f"https://www.google.com/maps/dir/?api=1&destination={encoded_dest}"
        )

        optimized_stops.append(
            OptimizedStop(
                stop_number=stop["stop_number"],
                address=stop["address"],
                arrival_time=stop["arrival_time"],
                time_window=stop["time_window"],
                slot=stop["slot"],
                maps_url=maps_url,
            )
        )

    return OptimizeRouteResponse(
        success=True,
        total_stops=len(optimized_stops),
        depot_address=request.depot_address,
        route=optimized_stops,
    )
